version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - api
      - db
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase # URL do banco de dados
  db:
    container_name: db
    image: postgres:latest # imagem do PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: higor # nome do usuário do banco de dados
      POSTGRES_PASSWORD: ngcash_eu_te_amo # senha do usuário do banco de dados
      POSTGRES_DB: mydatabase # nome do banco de dados
    volumes:
      - postgres_data:/var/lib/postgresql/data # monta um volume para armazenar os dados do PostgreSQL
    ports:
      - 5432:5432 # porta padrão do PostgreSQL
    networks:
      - app_network

# Define uma network, que permite que os containers se comuniquem
# entre si, usando o nome do container como um hostname
networks:
  app_network:
    external: true

volumes:
  postgres_data: # define o volume a ser usado para armazenar os dados do PostgreSQL
